# Generated by Django 3.2.16 on 2023-01-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='field1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='field2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['field1', 'field2'], name='services_su_field1_9296d9_idx'),
        ),
    ]
